version: 0.2

env:
  variables:
    SONAR_HOST_URL: "http://54.160.16.113:9000/"  # Your SonarQube URL
    SONAR_TOKEN: "squ_2a1acbdc7256116ab1f89e4e8339f7c8f0c78efb"  # Replace with your SonarQube token
    ECR_REPOSITORY_URI: "905418153772.dkr.ecr.ap-south-1.amazonaws.com/testweb"  # Replace with your ECR URI
    AWS_REGION: "ap-south-1"  # Replace with your AWS region
    TRIVY_VERSION: "0.22.0"

phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      echo "Installing Trivy"
      curl -sSL https://github.com/aquasecurity/trivy/releases/download/v${TRIVY_VERSION}/trivy_${TRIVY_VERSION}_Linux-64bit.tar.gz | tar -xz -C /usr/local/bin

      echo "Installing Sonar Scanner"
      curl -sSLo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
      unzip sonar-scanner.zip -d /opt/sonar-scanner

  pre_build:
    commands:
      echo "Logging into Amazon ECR"
      aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPOSITORY_URI

      echo "Setting up environment variables for SonarQube, EKS, and ECR"
      export SONAR_SCANNER_HOME=/opt/sonar-scanner/sonar-scanner-4.6.2.2472-linux
      export PATH=$PATH:$SONAR_SCANNER_HOME/bin

  build:
    commands:
      echo "Running SonarQube Scan"
      $SONAR_SCANNER_HOME/bin/sonar-scanner \
        -Dsonar.projectKey=your-project-key \
        -Dsonar.sources=. \
        -Dsonar.host.url=$SONAR_HOST_URL \
        -Dsonar.login=$SONAR_TOKEN

      echo "Building Docker image"
      docker build -t $ECR_REPOSITORY_URI:$CODEBUILD_RESOLVED_SOURCE_VERSION .

      echo "Pushing Docker image to ECR"
      docker push $ECR_REPOSITORY_URI:$CODEBUILD_RESOLVED_SOURCE_VERSION

      echo "Running Trivy security scan"
      trivy image --format json --output trivy-report.json $ECR_REPOSITORY_URI:$CODEBUILD_RESOLVED_SOURCE_VERSION

  post_build:
    commands:
      echo "Uploading Trivy scan report to S3"
      aws s3 cp trivy-report.json s3://test-trivy-reports/trivy-reports/${CODEBUILD_RESOLVED_SOURCE_VERSION}/trivy-report.json
